# Generated by Django 5.2.8 on 2025-11-17 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory_management', '0004_alter_profile_profile_pic_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='Inventory_management.profile'),
        ),
    ]
