# Generated by Django 5.2.8 on 2025-11-17 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory_management', '0006_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='sku',
        ),
    ]
