# Generated by Django 5.2.8 on 2025-11-18 10:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory_management', '0010_staff_is_active'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='salesrecord',
            old_name='created_at',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='salesrecord',
            name='customer_name',
        ),
        migrations.RemoveField(
            model_name='salesrecord',
            name='recorded_by',
        ),
        migrations.RemoveField(
            model_name='salesrecord',
            name='sale_date',
        ),
        migrations.RemoveField(
            model_name='salesrecord',
            name='total_price',
        ),
        migrations.RemoveField(
            model_name='salesrecord',
            name='unit_price',
        ),
        migrations.AddField(
            model_name='salesrecord',
            name='staff',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
